import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNavBarLayout from '@/layouts/sideNavBar.layout'
import { DataContextProvider } from '@/store/data'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex w-full">
          <aside>
            <SideNavBarLayout />
          </aside>
          <section className='w-full p-4'>
            <DataContextProvider>
              {children}
            </DataContextProvider>
          </section>
        </main>
      </body>
    </html>
  )
}
